#!/bin/bash

echo "Director MCP Server Setup"
echo "========================"
echo ""
echo "To use the Director MCP Server in Claude Code:"
echo ""
echo "1. Add the following to your Claude Code settings JSON:"
echo ""
cat claude-code-config.json
echo ""
echo ""
echo "2. Make sure the backend server is running:"
echo "   cd ../.. && npm start"
echo ""
echo "3. Restart Claude Code to load the MCP server"
echo ""
echo "4. In Claude Code, you'll see 'director' in the MCP servers list"
echo ""
echo "5. Start using Director tools directly:"
echo "   - First: mcp_set_workflow_context({ workflow_id: 'my-workflow', create_if_missing: true })"
echo "   - Then: Use any Director tool like dom_overview(), add_or_replace_nodes(), etc."
echo ""
echo "For more details, see README.md"