name: Scheduled Cleanup

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  # Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  trigger-cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run Database Cleanup Function
        id: cleanup
        run: |
          echo "Attempting to clean up raw videos older than 1 hour..."
          
          # Call the database function directly
          RESULT=$(curl -s -X POST \
            "https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/rest/v1/rpc/cleanup_raw_videos" \
            -H "apikey: ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json")
          
          echo "Cleanup result:"
          echo "$RESULT" | jq '.'
          
          # Count successful deletions
          DELETED_COUNT=$(echo "$RESULT" | jq '[.[] | select(.deleted == true)] | length')
          
          echo "Successfully cleaned up $DELETED_COUNT old raw video files."
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        continue-on-error: true
      
      - name: Log Completion
        run: |
          if [ "${{ steps.cleanup.outcome }}" == "success" ]; then
            echo "Scheduled cleanup completed successfully"
          else
            echo "Scheduled cleanup encountered issues - please check the logs"
          fi 